repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: stage-formatted
        name: stage formatted files
        entry: git add -u
        language: system
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: typecheck
        name: typecheck
        entry: pixi run typecheck
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: pytest
        name: pytest (testmon)
        entry: pixi run pytest tests --ignore=tests/benchmarks -x -q --testmon
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]